### ISSUE TITLE
[master] Step-35 and DFG benchmark abort if parameters are modified

### ISSUE THREAD

**Issue by sebglane** [j507/RotatingMHD#102]
After changing the maximum number of time steps or the final time in the input files, both programs abort relatively quickly and throw an exception. We should modify the input files at some point in order to have robust application. I guess that the maximum number of iterations allowed for the diffusion step solver must be increased or that the preconditioner type must be switched to a multigrid preconditioner.

**Comment by j507** [comment]
The maximum number of time steps is not really implemented in the `master` branch. I haven't ran a modified `step-35` but I did full runs of `DFG.cc` for the presentation, i.e. until `t=3000` with no problem. I do not see how changing the final time here would cause an abort. Could you post the `prm` file here that replicates the problem?

**Comment by sebglane** [comment]
Closing this because there are other issues, see #117.
