### ISSUE TITLE
[master] The execution of some applications fails

### ISSUE THREAD

**Issue by sebglane** [j507/RotatingMHD#117]
There are additional problems:

1. `MIT.cc` only performs two timesteps and reaches the final time after the second timestep.
2. `Christensen.cc` has an executation error which is related to the linear solver of the heat equation.
3. `DFG.cc` fails after the second timestep. The error occurs in the solve method of the diffusion step.
4. `step-35.cc` fails after the second timestep. The error occurs in the solve method of the diffusion step.

**Comment by j507** [comment]
The issue started in #112.

**Comment by sebglane** [comment]
Fixed in the branch `fix_117`

**Comment by sebglane** [comment]
Fixed in PR #122
