### ISSUE TITLE
[master] Use consistent number of quadrature points

### ISSUE THREAD

**Issue by sebglane** [j507/RotatingMHD#135]
The number of quadrature points should be consistently chosen everywhere inside the library. I think that an exact integration of the mass matrix with `QGauss<dim>(fe.degree +1)` is sufficient and the standard choice. In the analysis of the convergence test of `ThermalTGV.cc`, I realized that an overintegration can yield to artifacts causing several many headaches.

**Comment by j507** [comment]
Is the inconsistent use of quadrature points the cause of the positive convergence order then?

**Comment by sebglane** [comment]
Yes, see also my comments in #118

**Comment by sebglane** [comment]
Resolved in PR #143
